// Describe the title of your article by replacing "Tutorial template" with the page name you want to publish to in Confluence.
= Tutorial template
// Article variables (delete the `// comments` and add in the values)
:description: // Summarise what this tutorial is about in a sentence or two. What you put here is reused in the Goal section and included in HTML description tags.
:keywords: // These are comma-separated tags.
:experimental: // Enables UI Macros for Menu transitions and Keyboard shortcuts.

== Goal

{description}

== Before you start
// Delete this section if your readers can dive straight into the lesson without requiring any pre-requisite knowledge.
Make sure you meet the following pre-requisites before starting the tutorial steps:

* Pre-requisite one
* Pre-requisite two
* etc

'''

== Part 1 - <Part Title>

////
Introduce what your audience will learn in this step, then continue to write the steps in the tutorial.
You can choose one of these approaches to write your tutorial part:

* In a narrative style if your parts are short or you are using screenshots to do most of the talking.   
* In a "Goal > Steps > Outcome" structure to build a predictable flow in all your tutorial parts.

Whatever option you choose when designing your tutorial should be carried through in subsequent parts.
////

== Part 2 - <Part Title>

////
Continue the design approach you chose in the previous part and continue it through to the end of the tutorial.
////

== What you've learned

////
Summarise what knowledge the reader has gained by completing the tutorial, including a summary of each part's Goals (this is a good way to validate whether your tutorial has covered all you need it to.)
////
